feat: add husky pre commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,6 +2,10 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 branch="$(git rev-parse --abbrev-ref HEAD)"
+if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
+  echo "You can't commit directly to master/main branch"
+  exit 1
+fi
 
 #if [ "$branch" = "develop" ]; then
 #  echo "You can't commit directly to master branch"
