feat: add husky pre push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -9,5 +9,13 @@ then
   echo -e "\n\n🚫 You must use (git push origin $BRANCH) .\n\n" && exit 1
 fi
 
+if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
+then
+  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR." && exit 1
+fi
+
+echo -e ">> Finish checking branch name / Selesai mengecek nama branch.\n==="
+
+
 pnpm git-branch-is --not develop
   exit 1
