feat: add husky pre commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,15 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+#if [ "$branch" = "develop" ]; then
+#  echo "You can't commit directly to master branch"
+#  exit 1
+#fi
+
+pnpm git-branch-is --not master
+pnpm git-branch-is --not develop
+
+
 pnpm test run
